# Generated by Django 6.0.2 on 2026-09-12 16:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chorompo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do tratamento')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('duration_minutes', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duração em minutos')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='chorompo.company')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(verbose_name='Data e horário')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='chorompo.company')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='chorompo.patient', verbose_name='Paciente')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='chorompo.employee', verbose_name='Profissional')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='chorompo.treatment', verbose_name='Tratamento')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
    ]
