# Generated by Django 6.0.2 on 2026-09-12 17:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def rename_catalog_company_constraint(apps, schema_editor):
    # MySQL retains FK names when a table is renamed. Free the old Treatment
    # constraint name before creating the patient-purchase table with that name.
    if schema_editor.connection.vendor != "mysql":
        return
    catalog = apps.get_model("chorompo", "TreatmentCompany")
    table = catalog._meta.db_table
    field = catalog._meta.get_field("company")
    target_table = field.target_field.model._meta.db_table
    target_column = field.target_field.column
    new_name = "chorompo_catalog_company_fk"
    with schema_editor.connection.cursor() as cursor:
        constraints = schema_editor.connection.introspection.get_constraints(cursor, table)
    quote = schema_editor.quote_name
    for name, constraint in constraints.items():
        if constraint["columns"] == [field.column] and constraint.get("foreign_key") == (target_table, target_column) and name != new_name:
            schema_editor.execute(
                f"ALTER TABLE {quote(table)} DROP FOREIGN KEY {quote(name)}, "
                f"ADD CONSTRAINT {quote(new_name)} FOREIGN KEY ({quote(field.column)}) "
                f"REFERENCES {quote(target_table)} ({quote(target_column)})"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('chorompo', '0003_preserve_treatment_catalog'),
    ]

    operations = [
        migrations.RunPython(rename_catalog_company_constraint, migrations.RunPython.noop),
        migrations.AddField(
            model_name='treatmentcompany',
            name='fixed_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Custo fixo por unidade de tratamento, como aluguel, salários ou despesas gerais.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Custo fixo'),
        ),
        migrations.AddField(
            model_name='treatmentcompany',
            name='max_discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Porcentagem máxima de desconto que pode ser aplicada a este tratamento.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Desconto máximo (%)'),
        ),
        migrations.AddField(
            model_name='treatmentcompany',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço por sessão'),
        ),
        migrations.AddField(
            model_name='treatmentcompany',
            name='variable_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Custo variável por unidade de tratamento, como materiais ou insumos utilizados.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Custo variável'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='treatment_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='chorompo.treatmentcompany', verbose_name='Tratamento do catálogo'),
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do tratamento')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('qty_sessions', models.PositiveIntegerField(default=1, help_text='De 1 a 1.000 sessões por aquisição.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Quantidade de sessões')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor total adquirido')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Desconto (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='chorompo.company')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatments', to='chorompo.patient', verbose_name='Paciente')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_treatments', to='chorompo.treatmentcompany', verbose_name='Tratamento do catálogo')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='chorompo.treatment', verbose_name='Tratamento adquirido'),
        ),
        migrations.CreateModel(
            name='TreatmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número da sessão')),
                ('session_held', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1)], verbose_name='Sessão realizada')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data da realização')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='chorompo.treatment', verbose_name='Tratamento adquirido')),
            ],
            options={
                'ordering': ['session_number'],
            },
        ),
        migrations.CreateModel(
            name='EvolutionOfTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data da evolução')),
                ('notes', models.TextField(verbose_name='Evolução e observações')),
                ('uses_session', models.BooleanField(default=False, verbose_name='Registrar realização desta sessão')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evolutions', to='chorompo.employee', verbose_name='Profissional')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evolutions', to='chorompo.treatmentsession', verbose_name='Sessão')),
            ],
            options={
                'ordering': ['-date', '-created_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='chorompo.treatmentsession', verbose_name='Sessão adquirida'),
        ),
        migrations.AddConstraint(
            model_name='treatment',
            constraint=models.CheckConstraint(condition=models.Q(('qty_sessions__gte', 1), ('qty_sessions__lte', 1000)), name='valid_purchased_session_quantity'),
        ),
        migrations.AddConstraint(
            model_name='treatmentsession',
            constraint=models.UniqueConstraint(fields=('treatment', 'session_number'), name='unique_treatment_session_number'),
        ),
        migrations.AddConstraint(
            model_name='treatmentsession',
            constraint=models.CheckConstraint(condition=models.Q(('session_held__in', [0, 1])), name='session_used_at_most_once'),
        ),
        migrations.AddConstraint(
            model_name='treatmentsession',
            constraint=models.CheckConstraint(condition=models.Q(('session_number__gte', 1)), name='positive_session_number'),
        ),
    ]
