# Generated by Django 6.0.2 on 2026-09-17 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chorompo', '0004_treatmentcompany_fixed_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Pacote de tratamentos', max_length=100, verbose_name='Nome do pacote')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_packages', to='chorompo.company')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_packages', to='chorompo.patient', verbose_name='Paciente')),
            ],
        ),
        migrations.AddField(
            model_name='treatment',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treatments', to='chorompo.treatmentpackage', verbose_name='Pacote de compra'),
        ),
    ]
